name: Run npm test

on:
  push:
    branches:
    - main
    - release/*
jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Change to your Node.js version if different

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
